name: Virtual Library ETL Pipeline

on:
  schedule:
    # In production, they are scheduled 30 mins apart to ensure the queue is full
    - cron: '0 1 * * *'   # Harvester runs at 1:00 AM
    - cron: '30 1 * * *'  # Extractor runs at 1:30 AM
  workflow_dispatch:      

jobs:
  run-harvester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # UPDATED TO CLEAR WARNING

      - name: Setup Python
        uses: actions/setup-python@v5 # UPDATED TO CLEAR WARNING
        with:
          python-version: '3.10'

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install chromium

      - name: Create GCP Key File
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-key.json

      - name: Run Harvester
        run: python harvester.py
        
  run-extractor:
    # THE "NEEDS" LINE HAS BEEN REMOVED FOR PARALLEL EXECUTION
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # UPDATED TO CLEAR WARNING

      - name: Setup Python
        uses: actions/setup-python@v5 # UPDATED TO CLEAR WARNING
        with:
          python-version: '3.10'

      - name: Install Python Libraries
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install chromium

      - name: Create GCP Key File
        run: echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-key.json

      - name: Run Extractor Worker
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python extractor.py
